#pragma once

// clang-format off
// generated by /home/shelpam/Documents/projects/sqlpp23/scripts/sqlpp23-ddl2cpp --path-to-ddl table.sql --namespace schema --path-to-header-directory src/schema

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace schema {
  struct Assignment_ {
    struct Name {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(name, name);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    struct StartTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(start_time, start_time);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    struct EndTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(end_time, end_time);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(assignment, assignment);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Name,
               StartTime,
               EndTime>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<Assignment_>, Name>,
               sqlpp::column_t<sqlpp::table_t<Assignment_>, StartTime>,
               sqlpp::column_t<sqlpp::table_t<Assignment_>, EndTime>>;
  };
  using Assignment = ::sqlpp::table_t<Assignment_>;

} // namespace schema
