#pragma once

// clang-format off
// generated by /home/shelpam/Documents/projects/sqlpp23/scripts/sqlpp23-ddl2cpp --path-to-ddl table.sql --namespace schema --path-to-header-directory src/schema

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace schema {
  struct Submission_ {
    struct AssignmentName {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(assignment_name, assignment_name);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    struct StudentId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(student_id, student_id);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    struct SubmissionTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(submission_time, submission_time);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    struct Filepath {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(filepath, filepath);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    struct OriginalFilename {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(original_filename, original_filename);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(submission, submission);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               AssignmentName,
               StudentId,
               SubmissionTime,
               Filepath,
               OriginalFilename>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<Submission_>, AssignmentName>,
               sqlpp::column_t<sqlpp::table_t<Submission_>, StudentId>,
               sqlpp::column_t<sqlpp::table_t<Submission_>, SubmissionTime>,
               sqlpp::column_t<sqlpp::table_t<Submission_>, Filepath>,
               sqlpp::column_t<sqlpp::table_t<Submission_>, OriginalFilename>>;
  };
  using Submission = ::sqlpp::table_t<Submission_>;

} // namespace schema
